spring:
  application:
    name: coupon-merchant-admin
  datasource:
    url: jdbc:mysql://192.168.17.128:3306/coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.17.128
      port: 6379
server:
  port: 10010
  servlet:
    context-path:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.coupon


knife4j:
  enable: true
  setting:
    language: zh_cn

xxl-job:
  enable: true
  access-token: deault_token
  admin:
    address: http://localhost:8088/xxl-job-admin
  executor:
    application-name: coupon-merchant-admin
    ip: 127.0.0.1
    log_retention-days: 30
    port: 19999
#    log-path: E:/xxl-job-log


rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: oneCoupon_merchant_admin-859608205-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
